### ISSUE TITLE
테트리스 게임 페이지 수정 및 보완

### ISSUE THREAD

**Issue by seungineer** [HandTris/FE-HandTris#136]
## TO-DO
- [x] 개발에 사용하기 위해 있던 버튼 삭제
- [x] NEXT 버튼 위치 조정
- [x] Attack Line 추가
- [ ] Time 추가
- [x] 보드 상단 닉네임 추가
- [x] 핸드조이스틱 및 버튼 위치 조정
### 참고
![image](https://github.com/HandTris/FE-HandTris/assets/97353541/d8bf3655-89a3-4ea8-8ffa-1bea73176c92)

**Comment by seungineer** [comment]
## 참고
![image](https://github.com/HandTris/FE-HandTris/assets/97353541/947767b7-6bd9-4386-8503-d67ed96bab3a)
